services:
  - type: web
    name: inrl-md
    env: node
    branch: main
    repo: https://github.com/inrl-official/inrl-bot-md.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      - key: SESSION_ID
        sync: false
      - key: BOT_INFO
        value: inrl;bot;https://i.imgur.com/VIpl3q5.mp4
      - key: WARN_COUNT
        value: 3
      - key: STATUS_VIEW
        value: false
      - key: SAVE_STATUES
        value: true
      - key: STICKER_DATA
        value: INRL;MD
      - key: PREFIX
        value: [!,/.]
      - key: WORK_TYPE
        value: private
      - key: CHATBOT
        value: false
      - key: REACT
        value: command
      - key: AUDIO_DATA
        value: inrl;bot;https://i.imgur.com/VgxJeCm.jpeg
      - key: SUDO
        value: 919131652091 
      - key: DATABASE_URL
        sync: false
